// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "@storyblok/js";
import type { StoryblokRichtext, StoryblokAsset, StoryblokMultiasset, StoryblokMultilink } from "../storyblok.d.ts";
export interface AnimatedWord {
	word: string;
	component: "animated-word";
	_uid: string;
	[k: string]: unknown;
}

export interface AnimatedWords {
	animated_words?: AnimatedWord[];
	component: "animated-words";
	_uid: string;
	[k: string]: unknown;
}

export interface AnimatedWordsSection {
	eyebrow?: string;
	heading?: string;
	animated_words: AnimatedWord[];
	background?: StoryblokAsset;
	theme?: number | string;
	component: "animated-words-section";
	_uid: string;
	[k: string]: unknown;
}

export interface Article {
	title?: string;
	excerpt?: string;
	image?: StoryblokAsset;
	categories?: (ISbStoryData<Category> | string)[];
	wysiwyg?: (BannerWysiwyg | GalleryWysiwyg | ImageWysiwyg | TestimonialWysiwyg | TextWysiwyg | VideoWysiwyg)[];
	meta_title?: string;
	meta_desc?: string;
	body?: (
		| AnimatedWordsSection
		| ArticlesSection
		| CaseStudiesSection
		| ChecklistSection
		| ColouredContainerSection
		| ContactSection
		| FaqsSection
		| FeatureSection
		| FullWidthImageSection
		| ImageSection
		| IntroSection
		| KeyFeaturesSection
		| LogoCarouselSection
		| LogosSection
		| StatsSection
		| SubscribeSection
		| TestimonialsSection
		| TextAndImageSection
		| TextOverImageSection
		| TextSection
		| TiktokSection
	)[];
	author?: ISbStoryData<Author> | string;
	component: "article";
	_uid: string;
	[k: string]: unknown;
}

export interface ArticleOverview {
	showSort?: boolean;
	body?: (
		| AnimatedWordsSection
		| ArticlesSection
		| CaseStudiesSection
		| ChecklistSection
		| ColouredContainerSection
		| ContactSection
		| FaqsSection
		| FeatureSection
		| FullWidthImageSection
		| ImageSection
		| IntroSection
		| KeyFeaturesSection
		| LogoCarouselSection
		| LogosSection
		| StatsSection
		| SubscribeSection
		| TestimonialsSection
		| TextAndImageSection
		| TextOverImageSection
		| TextSection
		| TiktokSection
	)[];
	title?: string;
	meta_title?: string;
	meta_description?: string;
	excerpt?: string;
	image?: StoryblokAsset;
	button?: Button[];
	component: "article-overview";
	_uid: string;
	[k: string]: unknown;
}

export interface ArticlesSection {
	eyebrow?: string;
	heading?: string;
	body?: string;
	articles?: (ISbStoryData<Article> | string)[];
	filter_by_category?: (ISbStoryData<Category> | string)[];
	theme?: number | string;
	button?: Button[];
	component: "articles-section";
	_uid: string;
	[k: string]: unknown;
}

export interface Author {
	avatar?: StoryblokAsset;
	name: string;
	description?: string;
	linkedin?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
	component: "author";
	_uid: string;
	[k: string]: unknown;
}

export interface BannerWysiwyg {
	background?: number | string;
	richtext?: StoryblokRichtext;
	component: "banner-wysiwyg";
	_uid: string;
	[k: string]: unknown;
}

export interface Button {
	link: Exclude<StoryblokMultilink, { linktype?: "asset" }>;
	label: string;
	variant: "" | "primary" | "secondary" | "text-link";
	form_trigger?: boolean;
	component: "button";
	_uid: string;
	[k: string]: unknown;
}

export interface CaseStudiesSection {
	eyebrow?: string;
	heading?: string;
	body?: string;
	articles?: (ISbStoryData<CaseStudy> | string)[];
	theme?: number | string;
	button?: Button[];
	component: "case-studies-section";
	_uid: string;
	[k: string]: unknown;
}

export interface CaseStudy {
	industry?: {
		[k: string]: unknown;
	}[];
	wysiwyg?: (BannerWysiwyg | GalleryWysiwyg | ImageWysiwyg | TestimonialWysiwyg | TextWysiwyg | VideoWysiwyg)[];
	body?: (
		| AnimatedWordsSection
		| ArticlesSection
		| CaseStudiesSection
		| ChecklistSection
		| ColouredContainerSection
		| ContactSection
		| FaqsSection
		| FeatureSection
		| FullWidthImageSection
		| ImageSection
		| IntroSection
		| KeyFeaturesSection
		| LogoCarouselSection
		| LogosSection
		| StatsSection
		| SubscribeSection
		| TestimonialsSection
		| TextAndImageSection
		| TextOverImageSection
		| TextSection
		| TiktokSection
	)[];
	logo?: StoryblokAsset;
	title?: string;
	excerpt?: StoryblokRichtext;
	image?: StoryblokAsset;
	disclaimer?: string;
	meta_title?: string;
	meta_desc?: string;
	component: "case-study";
	_uid: string;
	[k: string]: unknown;
}

export interface CaseStudyOverview {
	title?: string;
	excerpt?: string;
	image?: StoryblokAsset;
	body?: (
		| AnimatedWordsSection
		| ArticlesSection
		| CaseStudiesSection
		| ChecklistSection
		| ColouredContainerSection
		| ContactSection
		| FaqsSection
		| FeatureSection
		| FullWidthImageSection
		| ImageSection
		| IntroSection
		| KeyFeaturesSection
		| LogoCarouselSection
		| LogosSection
		| StatsSection
		| SubscribeSection
		| TestimonialsSection
		| TextAndImageSection
		| TextOverImageSection
		| TextSection
		| TiktokSection
	)[];
	meta_title?: string;
	button?: Button[];
	component: "case-study-overview";
	_uid: string;
	[k: string]: unknown;
}

export interface Category {
	title?: string;
	excerpt?: string;
	image?: StoryblokAsset;
	name: string;
	body?: (
		| AnimatedWordsSection
		| ArticlesSection
		| CaseStudiesSection
		| ChecklistSection
		| ColouredContainerSection
		| ContactSection
		| FaqsSection
		| FeatureSection
		| FullWidthImageSection
		| ImageSection
		| IntroSection
		| KeyFeaturesSection
		| LogoCarouselSection
		| LogosSection
		| StatsSection
		| SubscribeSection
		| TestimonialsSection
		| TextAndImageSection
		| TextOverImageSection
		| TextSection
		| TiktokSection
	)[];
	meta_title?: string;
	meta_description?: string;
	component: "category";
	_uid: string;
	[k: string]: unknown;
}

export interface CategoryOverview {
	component: "category-overview";
	_uid: string;
	[k: string]: unknown;
}

export interface ChecklistSection {
	eyebrow?: string;
	heading?: string;
	checklist?: ListItem[];
	button?: Button[];
	theme?: number | string;
	component: "checklist-section";
	_uid: string;
	[k: string]: unknown;
}

export interface ColouredContainer {
	content: StoryblokRichtext;
	component: "coloured-container";
	_uid: string;
	[k: string]: unknown;
}

export interface ColouredContainerSection {
	eyebrow?: string;
	heading?: string;
	body?: StoryblokRichtext;
	sections?: ColouredContainer[];
	theme?: number | string;
	button?: Button[];
	component: "coloured-container-section";
	_uid: string;
	[k: string]: unknown;
}

export interface Config {
	header: Header[];
	footer: Footer[];
	cookie?: CookieConsent[];
	contact?: Contact[];
	component: "config";
	_uid: string;
	[k: string]: unknown;
}

export interface Contact {
	linkedin?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
	email?: Exclude<StoryblokMultilink, { linktype?: "asset" }>;
	phone?: string;
	address?: string;
	component: "contact";
	_uid: string;
	[k: string]: unknown;
}

export interface ContactSection {
	eyebrow?: string;
	heading?: string;
	theme?: number | string;
	linkedin?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
	email?: Exclude<StoryblokMultilink, { linktype?: "asset" }>;
	phone?: string;
	address?: string;
	component: "contact-section";
	_uid: string;
	[k: string]: unknown;
}

export interface CookieConsent {
	message?: StoryblokRichtext;
	component: "cookie-consent";
	_uid: string;
	[k: string]: unknown;
}

export interface Faq {
	question: string;
	answer: StoryblokRichtext;
	meta_title?: string;
	meta_description?: string;
	component: "faq";
	_uid: string;
	[k: string]: unknown;
}

export interface FaqsSection {
	eyebrow?: string;
	heading?: string;
	body?: string;
	faqs: (ISbStoryData<Faq> | string)[];
	theme?: number | string;
	button?: Button[];
	component: "faqs-section";
	_uid: string;
	[k: string]: unknown;
}

export interface FeatureSection {
	name?: string;
	theme?: number | string;
	component: "feature-section";
	_uid: string;
	[k: string]: unknown;
}

export interface Footer {
	menu?: MenuSection[];
	body?: StoryblokRichtext;
	mandatories?: Link[];
	linkedin?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
	youtube?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
	tiktok?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
	instagram?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
	component: "footer";
	_uid: string;
	[k: string]: unknown;
}

export interface FullWidthImageSection {
	image?: StoryblokAsset;
	component: "full-width-image-section";
	_uid: string;
	[k: string]: unknown;
}

export interface GalleryWysiwyg {
	gallery: StoryblokMultiasset;
	component: "gallery-wysiwyg";
	_uid: string;
	[k: string]: unknown;
}

export interface Header {
	menu?: (MenuSection | MenuLink)[];
	buttons?: Button[];
	phone?: string;
	component: "header";
	_uid: string;
	[k: string]: unknown;
}

export interface Homepage {
	title: string;
	animated_title?: AnimatedWord[];
	subheading?: string;
	buttons?: Button[];
	image?: StoryblokAsset;
	excerpt?: string;
	body?: (
		| AnimatedWordsSection
		| ArticlesSection
		| CaseStudiesSection
		| ChecklistSection
		| ColouredContainerSection
		| ContactSection
		| FaqsSection
		| FeatureSection
		| FullWidthImageSection
		| ImageSection
		| IntroSection
		| KeyFeaturesSection
		| LogoCarouselSection
		| LogosSection
		| StatsSection
		| SubscribeSection
		| TestimonialsSection
		| TextAndImageSection
		| TextOverImageSection
		| TextSection
		| TiktokSection
	)[];
	meta_title?: string;
	meta_description?: string;
	component: "homepage";
	_uid: string;
	[k: string]: unknown;
}

export interface ImageSection {
	images?: StoryblokMultiasset;
	theme?: number | string;
	component: "image-section";
	_uid: string;
	[k: string]: unknown;
}

export interface ImageWysiwyg {
	image: StoryblokAsset;
	caption?: string;
	component: "image-wysiwyg";
	_uid: string;
	[k: string]: unknown;
}

export interface Industry {
	title?: string;
	excerpt?: string;
	image?: StoryblokAsset;
	name: string;
	body?: (
		| AnimatedWordsSection
		| ArticlesSection
		| CaseStudiesSection
		| ChecklistSection
		| ColouredContainerSection
		| ContactSection
		| FaqsSection
		| FeatureSection
		| FullWidthImageSection
		| ImageSection
		| IntroSection
		| KeyFeaturesSection
		| LogoCarouselSection
		| LogosSection
		| StatsSection
		| SubscribeSection
		| TestimonialsSection
		| TextAndImageSection
		| TextOverImageSection
		| TextSection
		| TiktokSection
	)[];
	meta_title?: string;
	meta_description?: string;
	component: "industry";
	_uid: string;
	[k: string]: unknown;
}

export interface IndustryOverview {
	component: "industry-overview";
	_uid: string;
	[k: string]: unknown;
}

export interface IntroSection {
	eyebrow?: string;
	heading?: string;
	content?: StoryblokRichtext;
	theme?: number | string;
	button?: Button[];
	component: "intro-section";
	_uid: string;
	[k: string]: unknown;
}

export interface KeyFeaturesSection {
	heading?: string;
	body?: StoryblokRichtext;
	buttons?: Button[];
	isVertical?: boolean;
	features?: KeyPoint[];
	theme?: number | string;
	component: "key-features-section";
	_uid: string;
	[k: string]: unknown;
}

export interface KeyPoint {
	icon?: string;
	heading: string;
	body?: StoryblokRichtext;
	button?: Button[];
	component: "key-point";
	_uid: string;
	[k: string]: unknown;
}

export interface Link {
	label: string;
	link: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
	component: "link";
	_uid: string;
	[k: string]: unknown;
}

export interface ListItem {
	text: string;
	component: "list-item";
	_uid: string;
	[k: string]: unknown;
}

export interface LogoCarouselSection {
	eyebrow?: string;
	heading?: string;
	body?: string;
	logos: StoryblokMultiasset;
	theme?: number | string;
	component: "logo-carousel-section";
	_uid: string;
	[k: string]: unknown;
}

export interface LogosSection {
	heading?: string;
	content?: StoryblokRichtext;
	theme?: number | string;
	logos: StoryblokMultiasset;
	component: "logos-section";
	_uid: string;
	[k: string]: unknown;
}

export interface MenuLink {
	label: string;
	description?: string;
	link: Exclude<StoryblokMultilink, { linktype?: "asset" }>;
	component: "menu-link";
	_uid: string;
	[k: string]: unknown;
}

export interface MenuSection {
	heading: string;
	items?: MenuLink[];
	component: "menu-section";
	_uid: string;
	[k: string]: unknown;
}

export interface Page {
	type?: "primary" | "secondary";
	title: string;
	excerpt?: string;
	image?: StoryblokAsset;
	button?: Button[];
	body?: (
		| AnimatedWordsSection
		| ArticlesSection
		| CaseStudiesSection
		| ChecklistSection
		| ColouredContainerSection
		| ContactSection
		| FaqsSection
		| FeatureSection
		| FullWidthImageSection
		| ImageSection
		| IntroSection
		| KeyFeaturesSection
		| LogoCarouselSection
		| LogosSection
		| StatsSection
		| SubscribeSection
		| TestimonialsSection
		| TextAndImageSection
		| TextOverImageSection
		| TextSection
		| TiktokSection
	)[];
	meta_title?: string;
	meta_description?: string;
	component: "page";
	_uid: string;
	[k: string]: unknown;
}

export interface Stat {
	prefix?: string;
	value: string;
	suffix?: string;
	formatNumber?: boolean;
	description: string;
	component: "stat";
	_uid: string;
	[k: string]: unknown;
}

export interface StatsSection {
	heading?: string;
	stats?: Stat[];
	theme?: number | string;
	countNumbers?: boolean;
	component: "stats-section";
	_uid: string;
	[k: string]: unknown;
}

export interface SubscribeSection {
	heading?: string;
	body?: string;
	theme?: number | string;
	component: "subscribe-section";
	_uid: string;
	[k: string]: unknown;
}

export interface Testimonial {
	author?: string;
	role?: string;
	avatar?: StoryblokAsset;
	content?: string;
	company?: StoryblokAsset;
	component: "testimonial";
	_uid: string;
	[k: string]: unknown;
}

export interface TestimonialsSection {
	eyebrow?: string;
	heading?: string;
	body?: string;
	testimonials: (ISbStoryData<Testimonial> | string)[];
	theme?: number | string;
	component: "testimonials-section";
	_uid: string;
	[k: string]: unknown;
}

export interface TestimonialWysiwyg {
	testimonial: ISbStoryData<Testimonial> | string;
	component: "testimonial-wysiwyg";
	_uid: string;
	[k: string]: unknown;
}

export interface TextAndImageSection {
	eyebrow?: string;
	is_reverse?: boolean;
	heading?: string;
	body: StoryblokRichtext;
	buttons?: Button[];
	image: StoryblokAsset;
	theme?: number | string;
	component: "text-and-image-section";
	_uid: string;
	[k: string]: unknown;
}

export interface TextOverImageSection {
	eyebrow?: string;
	heading?: string;
	body: StoryblokRichtext;
	buttons?: Button[];
	image: StoryblokAsset;
	isContained?: boolean;
	component: "text-over-image-section";
	_uid: string;
	[k: string]: unknown;
}

export interface TextSection {
	eyebrow?: string;
	heading?: string;
	body: StoryblokRichtext;
	buttons?: Button[];
	theme?: number | string;
	isCenter?: boolean;
	component: "text-section";
	_uid: string;
	[k: string]: unknown;
}

export interface TextWysiwyg {
	richtext: StoryblokRichtext;
	component: "text-wysiwyg";
	_uid: string;
	[k: string]: unknown;
}

export interface Tiktok {
	url?: string;
	component: "tiktok";
	_uid: string;
	[k: string]: unknown;
}

export interface TiktokSection {
	eyebrow?: string;
	body?: string;
	heading?: string;
	theme?: number | string;
	component: "tiktok-section";
	_uid: string;
	[k: string]: unknown;
}

export interface VideoWysiwyg {
	video: StoryblokAsset;
	component: "video-wysiwyg";
	_uid: string;
	[k: string]: unknown;
}

export type ContentType =
	| Article
	| ArticleOverview
	| Author
	| CaseStudy
	| CaseStudyOverview
	| Category
	| CategoryOverview
	| Config
	| Faq
	| Homepage
	| Industry
	| IndustryOverview
	| Page
	| Testimonial;
